# ================================
# Space Finder - Dev Profile
# Used when running inside Docker
# ================================

# Database (injected by docker-compose environment vars)
#spring.datasource.url=jdbc:postgresql://localhost:5432/space_finder?createDatabaseIfNotExist=true
spring.datasource.url=jdbc:postgresql://trolley.proxy.rlwy.net:11661/railway
spring.datasource.username=postgres
spring.datasource.password=jKCVRDYoWejnENjKqQGtZidCXvShyVNQ
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.application.name=spacefinder-backend

# Server
server.port=8081

# Logging
logging.level.com.spacefinder=DEBUG
logging.level.org.springframework.security=DEBUG

# Swagger / OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.url=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true