# ================================
# Space Finder - Profile Setup
# ================================

spring.application.name=spacefinder-backend

# Image upload limits
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB