--
-- PostgreSQL database dump
--

\restrict vQN36Bynp42NQoC9ZRSkWMwE6hPcMvRmYODTkUiJtYeqQHpxxejC8UkC56gL4XK

-- Dumped from database version 16.13
-- Dumped by pg_dump version 16.13

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: bookings; Type: TABLE; Schema: public; Owner: spacefinder_user
--

CREATE TABLE public.bookings (
    booking_id bigint NOT NULL,
    id bigint NOT NULL
);


ALTER TABLE public.bookings OWNER TO spacefinder_user;

--
-- Name: bookings_booking_id_seq; Type: SEQUENCE; Schema: public; Owner: spacefinder_user
--

ALTER TABLE public.bookings ALTER COLUMN booking_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bookings_booking_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bookings_id_seq; Type: SEQUENCE; Schema: public; Owner: spacefinder_user
--

ALTER TABLE public.bookings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bookings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: properties; Type: TABLE; Schema: public; Owner: spacefinder_user
--

CREATE TABLE public.properties (
    property_id bigint NOT NULL,
    description character varying(255),
    location character varying(255),
    price double precision,
    status character varying(255),
    title character varying(255),
    id bigint NOT NULL,
    size double precision
);


ALTER TABLE public.properties OWNER TO spacefinder_user;

--
-- Name: properties_id_seq; Type: SEQUENCE; Schema: public; Owner: spacefinder_user
--

ALTER TABLE public.properties ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.properties_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: properties_property_id_seq; Type: SEQUENCE; Schema: public; Owner: spacefinder_user
--

ALTER TABLE public.properties ALTER COLUMN property_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.properties_property_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: spacefinder_user
--

CREATE TABLE public.users (
    user_id bigint NOT NULL,
    email character varying(255),
    name character varying(255),
    password_hash character varying(255),
    role character varying(255),
    status character varying(255),
    id bigint NOT NULL,
    password character varying(255),
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'AGENT'::character varying, 'USER'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO spacefinder_user;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: spacefinder_user
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: spacefinder_user
--

ALTER TABLE public.users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: bookings; Type: TABLE DATA; Schema: public; Owner: spacefinder_user
--

COPY public.bookings (booking_id, id) FROM stdin;
\.


--
-- Data for Name: properties; Type: TABLE DATA; Schema: public; Owner: spacefinder_user
--

COPY public.properties (property_id, description, location, price, status, title, id, size) FROM stdin;
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: spacefinder_user
--

COPY public.users (user_id, email, name, password_hash, role, status, id, password) FROM stdin;
\.


--
-- Name: bookings_booking_id_seq; Type: SEQUENCE SET; Schema: public; Owner: spacefinder_user
--

SELECT pg_catalog.setval('public.bookings_booking_id_seq', 1, false);


--
-- Name: bookings_id_seq; Type: SEQUENCE SET; Schema: public; Owner: spacefinder_user
--

SELECT pg_catalog.setval('public.bookings_id_seq', 1, false);


--
-- Name: properties_id_seq; Type: SEQUENCE SET; Schema: public; Owner: spacefinder_user
--

SELECT pg_catalog.setval('public.properties_id_seq', 1, false);


--
-- Name: properties_property_id_seq; Type: SEQUENCE SET; Schema: public; Owner: spacefinder_user
--

SELECT pg_catalog.setval('public.properties_property_id_seq', 1, false);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: spacefinder_user
--

SELECT pg_catalog.setval('public.users_id_seq', 1, false);


--
-- Name: users_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: spacefinder_user
--

SELECT pg_catalog.setval('public.users_user_id_seq', 1, false);


--
-- Name: bookings bookings_pkey; Type: CONSTRAINT; Schema: public; Owner: spacefinder_user
--

ALTER TABLE ONLY public.bookings
    ADD CONSTRAINT bookings_pkey PRIMARY KEY (booking_id);


--
-- Name: properties properties_pkey; Type: CONSTRAINT; Schema: public; Owner: spacefinder_user
--

ALTER TABLE ONLY public.properties
    ADD CONSTRAINT properties_pkey PRIMARY KEY (property_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: spacefinder_user
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- PostgreSQL database dump complete
--

\unrestrict vQN36Bynp42NQoC9ZRSkWMwE6hPcMvRmYODTkUiJtYeqQHpxxejC8UkC56gL4XK

