# ================================
# Space Finder - Dev Profile
# Used when running inside Docker
# ================================

#Base app URL
 app.base-url=https://localhost:8080

# Database (injected by docker-compose environment vars)
spring.datasource.url=jdbc:postgresql://spacefinder-db:5432/spacefinder?createDatabaseIfNotExist=true
spring.datasource.username=spacefinder_user
spring.datasource.password=spacefinder_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.application.name=spacefinder-backend

# Server
server.port=8080

# Logging
logging.level.com.spacefinder=DEBUG
logging.level.org.springframework.security=DEBUG

# Swagger / OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.url=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
