# ================================
# Space Finder - Dev Profile
# Used when running inside Docker
# ================================

#Base app URL
app.base-url=http://localhost:8081

# Database (injected by docker-compose environment vars)
#spring.datasource.url=jdbc:postgresql://localhost:5432/space_finder?createDatabaseIfNotExist=true
spring.datasource.url=jdbc:postgresql://trolley.proxy.rlwy.net:11661/railway
spring.datasource.username=postgres
spring.datasource.password=jKCVRDYoWejnENjKqQGtZidCXvShyVNQ
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.application.name=spacefinder-backend

# Local Server
server.port=8081

# Logging
logging.level.com.spacefinder=DEBUG
logging.level.org.springframework.security=DEBUG

# Swagger / OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.url=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# Cloudflare R2
cloudflare.r2.access-key=eaf5d44e0ac1de1deae8bf21bb8128b1
cloudflare.r2.secret-key=a459d5b104af1e7441623279d279e5b782f596e4bc2b34df78ec5f5a3b92da14
cloudflare.r2.s3-url=https://9b54a861f42bfbc74fb010857bf1d49a.r2.cloudflarestorage.com
cloudflare.r2.bucket=spacefinder-images
cloudflare.r2.public-url=https://pub-9181cd831bb14744922017e494096550.r2.dev